version: 2

sources:
  - name: worldbank_data_challenge
    database: postgres
    schema: public
    tables:
      - name: gdp_alldata
        columns:
          - name: countryiso3code
            data_tests:
              - not_null
          - name: date
            data_tests:
              - not_null
