services:
    db:
        image: postgres
        # restart: unless-stopped
        hostname: "db"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
        ports:
            - '5432:5432'
        # volumes:
        #     - pgdata:/var/lib/postgresql/data
    etl:
        build: ./app .
        depends_on:
            - db
        command: python /app/job.py
# volumes:
#     pgdata:
