services:
    db:
        image: postgres
        hostname: "db"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
        ports:
            - '5432:5432'
    etl:
        build: ./app .
        depends_on:
            - db
        command: python /app/job.py
