name: dbt CI pipeline
on: [push, pull_request]
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: install Python dependencies
        run: pip install --no-cache-dir -r .github\workflows\requirements.txt
      - name: install dbt deps
        run: dbt deps
      - name: compile queries
        run: dbt compile
