name: dbt CI pipeline
on: [push, pull_request]
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".github/workflows/requirements.txt"
      - name: compile queries
        run: dbt compile
